# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    
    - name: Build & Deploy    
      env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.REMOTE_HOST}}
            USER_NAME: ${{secrets.REMOTE_USER}}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -r build/ ubuntu@3.86.48.204:/tmp/
      
      # with:         
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: "build/"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: "/home/ubuntu"
          

#==============================================================
# jobs:
#   build:
#     name: Deploy to EC2 on master branch push
#     runs-on: ubuntu-latest 

#     strategy:
#       matrix:
#         node-version: [20.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#         REMOTE_HOST: ${{ secrets.HOST_DNS }}
#         REMOTE_USER: ${{ secrets.USERNAME }}
#         TARGET: ${{ secrets.TARGET_DIR }}
#     - run: npm ci
#     - run: npm run build 

